# Dataset parameters
dataset: Standard
dataset_path_train: ../../data/AHN4_34EN2_18/train
dataset_path_test: ../../data/AHN4_34EN2_18/test
dataset_path_validation: ../../data/AHN4_34EN2_18/val
path_output: ../../data/AHN4_34EN2_18/output
saving_path: "../../data/AHN4_34EN2_18/saved"
ignored_labels: []
label_continue: false
label_to_names:
  0: A
  1: B
  2: C
  3: D
  4: E

num_votes: 100
num_classes: null
dataset_task: ''

# Number of CPU threads for the input pipeline
input_threads: 7

# Architecture definition
architecture:
  - simple
  - resnetb
  - resnetb_strided
  - resnetb
  - resnetb
  - resnetb_strided
  - resnetb
  - resnetb
  - resnetb_strided
  - resnetb_deformable
  - resnetb_deformable
  - resnetb_deformable_strided
  - resnetb_deformable
  - resnetb_deformable
  - nearest_upsample
  - unary
  - nearest_upsample
  - unary
  - nearest_upsample
  - unary
  - nearest_upsample
  - unary

# KPConv parameters
num_kernel_points: 15
in_radius: 10.2
first_subsampling_dl: 0.3
conv_radius: 2.5
deform_radius: 5.0
KP_extent: 1.2
KP_influence: linear
aggregation_mode: sum
first_features_dim: 128
in_features_dim: 5
modulated: false
use_batch_norm: true
batch_norm_momentum: 0.02
deform_fitting_mode: point2point
deform_fitting_power: 1.0
deform_lr_factor: 0.1
repulse_extent: 1.2

# Training parameters
max_epoch: 50
epoch_steps: 50
validation_size: 50
checkpoint_gap: 1

learning_rate: 0.01
momentum: 0.98
lr_decays:
  1: 0.9810838814600102
  2: 0.9810838814600102
grad_clip_norm: 100.0
batch_num: 6
augment_scale_anisotropic: true
augment_symmetries:
  - true
  - false
  - false
augment_rotation: vertical
augment_scale_min: 0.9
augment_scale_max: 1.1
augment_noise: 0.001
augment_color: 0.8
segloss_balance: none
saving: true

