dataset: Standard 
dataset_path_train: ../../data/train
dataset_path_test: ../../data/test
dataset_path_validation: ../../data/val
path_output: ../../data/results/
saving_path: "../../results/saved_model" 
ignored_labels: [] 
label_continue: false 
label_to_names: 
  0: Floor
  1: Ceiling
  2: Wall
  3: Beam
  4: Column
  5: Windows
  6: Opening 
  7: None
  8: None
  9: None
  10: Unknown class
  11: None
  12: Clutter
  13: None
  14: None
  15: None
  16: None 
  17: None
  18: None
  19: None
  20: Extinguisher
  21: None
  22: None
  23: None
  24: Unknown class 2
  25: Stepladder
  26: Stairs

num_votes: 100
num_classes: null 
dataset_task: '' 

input_threads: 10

architecture:
  - simple
  - resnetb
  - resnetb_strided
  - resnetb
  - resnetb
  - resnetb_strided
  - resnetb
  - resnetb
  - resnetb_strided
  - resnetb_deformable
  - resnetb_deformable
  - resnetb_deformable_strided
  - resnetb_deformable
  - resnetb_deformable
  - nearest_upsample
  - unary
  - nearest_upsample
  - unary
  - nearest_upsample
  - unary
  - nearest_upsample
  - unary
  

num_kernel_points: 15 
in_radius: 1.2  
first_subsampling_dl: 0.03
conv_radius: 2.5 
deform_radius: 5.0 
KP_extent: 1.2 
KP_influence: linear 
aggregation_mode: sum 
first_features_dim: 128 
in_features_dim: 5
modulated: false 
use_batch_norm: true 
batch_norm_momentum: 0.02 
deform_fitting_mode: point2point 
deform_fitting_power: 1.0 
deform_lr_factor: 0.1 
repulse_extent: 1.2 


max_epoch: 100 
epoch_steps: 50
validation_size: 20
checkpoint_gap: 20

learning_rate: 0.01
momentum: 0.98
lr_decays:
  1: 0.9810838814600102
  2: 0.9810838814600102
grad_clip_norm: 100.0 
batch_num: 6 
augment_scale_anisotropic: true 
augment_symmetries: 
  - true
  - false
  - false
augment_rotation: vertical 
augment_scale_min: 0.9 
augment_scale_max: 1.1 
augment_noise: 0.001 
augment_color: 0.8 
segloss_balance: none 
saving: true 

